#!/bin/sh
#SBATCH -p amd_256
#SBATCH -N 1
#SBATCH -n 64
#SBATCH -J pmdReA
#SBATCH -e %J_err.log
#SBATCH -o %J_out.log
python WGBS_PMD_reanalysis_chr.py chr1 275406953 &
python WGBS_PMD_reanalysis_chr.py chr2 248966461 &
python WGBS_PMD_reanalysis_chr.py chr3 223996068 &
python WGBS_PMD_reanalysis_chr.py chr4 119216639 &
python WGBS_PMD_reanalysis_chr.py chr5 107836144 &
python WGBS_PMD_reanalysis_chr.py chr6 116888256 &
python WGBS_PMD_reanalysis_chr.py chr7 100009711 &
python WGBS_PMD_reanalysis_chr.py chr8 90615088 &
python WGBS_PMD_reanalysis_chr.py chr9 94583238 &
python WGBS_PMD_reanalysis_chr.py chr10 86377204 &
python WGBS_PMD_reanalysis_chr.py chr11 62170480 &
python WGBS_PMD_reanalysis_chr.py chr12 79028859 &
python WGBS_PMD_reanalysis_chr.py chr13 82951069 &
python WGBS_PMD_reanalysis_chr.py chr14 62568341 &
python WGBS_PMD_reanalysis_chr.py chr15 80783214 &
python WGBS_PMD_reanalysis_chr.py chr16 71693149 &
python WGBS_PMD_reanalysis_chr.py chr17 72251135 &
python WGBS_PMD_reanalysis_chr.py chr18 68494538 &
python WGBS_PMD_reanalysis_chr.py chr19 60445663 &
python WGBS_PMD_reanalysis_chr.py chr20 51049468 &
python WGBS_PMD_reanalysis_chr.py chr21 49987992 &
python WGBS_PMD_reanalysis_chr.py chr22 50780147 &
python WGBS_PMD_reanalysis_chr.py chr23 62282865 &
python WGBS_PMD_reanalysis_chr.py chr24 41976827 &
python WGBS_PMD_reanalysis_chr.py chr25 45223504 &
python WGBS_PMD_reanalysis_chr.py chr26 44047080 &
wait